### ISSUE TITLE
Multiple input args of the same time

### ISSUE THREAD

**Issue by jsiebern** [reasonml-community/graphql_ppx#119]
A query like this:
```reason
module MyQuery = [%graphql
  {|
  query ($arg: VariousScalarsInput!, $arg2: VariousScalarsInput!) {
    scalarsInput(arg: $arg)
    more: scalarsInput(arg: $arg2)
  }
|}
];
```

Generates the following error:
```
File "_none_", line 0:
Error: Multiple definition of the type name t_variables_VariousScalarsInput.
       Names must be unique in a given structure or signature.
```

Generated input types should be re-used if possible.

**Comment by jfrolich** [comment]
They should be reused. I think they just need to be deduplicated in the type generation. Good find!

**Comment by jfrolich** [comment]
Fixed here: https://github.com/reasonml-community/graphql_ppx/commit/f3a059b127d4c5cc61a2d2938976d3f7f67e845c
