### ISSUE TITLE
Throw an error on invalid default values

### ISSUE THREAD

**Issue by jsiebern** [reasonml-community/graphql_ppx#124]
Example Schema:
```graphql
  optionalInputArgs(
    required: String!
    optional: String
    anotherRequired: String!
  ): String!
```

Example Code:
```reason
module MyQuery = [%graphql
  {|
  mutation MyMutation($required: String!) {
    optionalInputArgs(required: $required, anotherRequired: 5)
  }
|}
];
```

`anotherRequired` is given a default `Int` instead of a `String`. Checking these for the default scalars should be straight forward. An error might be overkill, but we should throw a warning at least.

**Comment by jfrolich** [comment]
I actually think an error would make sense because it's incorrect to pass the wrong type.
