### ISSUE TITLE
JSON/YML configuration file

### ISSUE THREAD

**Issue by baransu** [reasonml-community/graphql_ppx#16]
Right now the amount of configuration is not that huge. Mostly we have
- verbose flag
- custom `graphql_schema.json` file
- apollo mode

but I expect in future to have more options like #5 or ability to specify global decoder for `__typename` (https://github.com/apollographql/reason-apollo/issues/157).

It would be more readable than passing flags to ppx or setting env variables.

**Comment by romanschejbal** [comment]
This would be really great, we have a monorepo setup and right now we have to include custom graphql_schema.json env variable override in every package and for every script which is quite repetitive.

**Comment by baransu** [comment]
I think JSON format will be better than YAML although JSON doesn't support comments which can be helpful.

**Comment by johnhaley81** [comment]
@baransu what do you think about something that loads `graphql_ppx.config.(js|json)`? That way you could have either a JSON file or something programmatic in a JS file?

**Comment by jfrolich** [comment]
I like the approach of folding the configuration in the `bsconfig.json` file (like `gentype`). A `js` configuration would be not practical as the configuration needs to be known pre-compile.

**Comment by baransu** [comment]
@jfrolich Totally agree with you! `bsconfig.json` is the best place for that for now 😉
