### ISSUE TITLE
OCaml 4.08+ support

### ISSUE THREAD

**Issue by anmonteiro** [reasonml-community/graphql_ppx#22]
Thanks for getting this project moving. Right now it doesn't seem like it's possible to depend on this package in newer versions of OCaml. I had to add the following to my esy resolutions:

```json
    "@baransu/graphql_ppx_re": {
      "source": "baransu/graphql_ppx_re:esy.json#c7fab6c",
      "override": {
        "build": "dune build -p graphql_ppx",
        "dependencies": {
          "@opam/ocaml-migrate-parsetree": "*",
          "@esy-ocaml/reason": "*",
          "refmterr": null
        }
      }
    }
```

I think these could get integrated in master. I don't know what refmterr is but it just doesn't build on OCaml 4.09 which is what I was testing, and removing it works fine. The `esy.json` also looks weird, and many of its dependencies are _very_ outdated (e.g. Menhir, OMP). I can submit an enhancement PR if you want.

**Comment by baransu** [comment]
Menhir version was hardcoded because of failing 4.02 tests on Windows and I probably left it like this for current esy.json.

You’re far more experienced and understand how thinks should be. Would be amazing if you could send a PR! 🚀
