### ISSUE TITLE
Add makeVariables and definition documentation

### ISSUE THREAD

**Issue by baransu** [reasonml-community/graphql_ppx#55]
- `makeVariables` PR: https://github.com/baransu/graphql_ppx_re/pull/35
- `definition` PR: https://github.com/baransu/graphql_ppx_re/pull/48

**Comment by dylanirlbeck** [comment]
@baransu Is there any documentation out currently for `makeVariables`? If there is anywhere you can point me to in order to get a better understanding before formal documentation is published, I'd appreciate it. Thanks in advance!

**Comment by jfrolich** [comment]
MakeVariables is similar to make, just creating the variables.

**Comment by jfrolich** [comment]
Closing for now
