### ISSUE TITLE
vscode-reasonml doesn't recognize graphql_ppx_re

### ISSUE THREAD

**Issue by selenir** [reasonml-community/graphql_ppx#56]
When using [vscode-reasonml](https://github.com/reasonml-editor/vscode-reasonml) plugin it shows an merlin error saying `Uninterpreted extension 'graphql'` when using the ppx. Also type hinting for resulting module doesn't work. Tested on both bucklescript 5.2.1 and 7.0.1. However, mhalin/graphql_ppx seems to work fine.

To reproduce just create empty project with graphql_ppx and any graphql_schema.json and try to use it. Project builds just fine, but the plugin keeps complaining.

**Comment by kamilkuz** [comment]
I have the same issue !
Good to fix it

**Comment by ZielonyBuszmen** [comment]
I have the same issue too! Bump Up.

**Comment by baransu** [comment]
Thank you for reporting the issue. I'll investigate.

**Comment by simonkberg** [comment]
Note that vscode-reasonml is [unmaintained](https://github.com/reasonml-editor/vscode-reasonml/blob/master/README.md). [reason-language-server](https://github.com/jaredly/reason-language-server) is the recommended replacement, but it doesn't seem to work well with this ppx either.

**Comment by kamilkuz** [comment]
@baransu any news ?

**Comment by baransu** [comment]
@kamilkuz Could you provide more detailed information? I'm using `reason-language-server` on a daily basis and have no issues with `graphql_ppx_re`. Have you tried that extension?

**Comment by selenir** [comment]
@baransu Hey, thanks for quick response. I have used reason-language-server in the past, but after some update it stopped working for me (ctrl + click code navigation wouldn't work) so I changed it to vscode-reasonml which works fine. Since then I've tried few times with different versions but I can't get it to work on Linux.

Also, what version of bucklescript do you use? I think they recently changed something with PPXes in 6 or 7 so it also may be related.

**Comment by baransu** [comment]
I'm using bs-platform 7 and 5.2 across different projects.

**Comment by sgrove** [comment]
This is also a problem with emacs, merlin (`3.3.3`), and graphql_ppx_re (`0.4.6`), bs-platform(`7.0.1`): `Uninterpreted extension 'graphql'.`

Looking into why now.

**Comment by jfrolich** [comment]
AFAK this works now
