### ISSUE TITLE
Add ability to provide serializers for custom scalars

### ISSUE THREAD

**Issue by nirvdrum** [reasonml-community/graphql_ppx#63]
I'm using Hasura as my GraphQL server and use UUIDs for all of my object IDs. This may be a bug or quirk of Hasura, but instead of using the standard `ID` GraphQL type it reports these as a custom scalar type named `uuid`. The only real way to interact with these values is as strings. While I can use `Js.Json.decodeString` and `Js.Json.string` to deal with them, it's really tedious. And since virtually every response from the GraphQL server will include one of these `uuid` values, it'd be handy if I could just provide serializers for the `uuid` type that would apply to all my queries.

**Comment by baransu** [comment]
Yes, this is really good idea. I have the same problem with `Long` scalar coming from `sangria-graphql`. Probably the best place for that would be to have a configuration file (#16) and place it there.

I'm afraid I won't have time to work on this particular feature but if you would like to send PR I would be more than happy to review and assist you along the way 🙂

**Comment by nirvdrum** [comment]
I'm happy to give it a shot. I was happy to see that I was able to build and run the tests without much hassle. I was a little worried given the difficulty I had with the older `graphql_ppx` project.

Do you have any concrete ideas on what you think this would look like in a configuration file? At first glance, I was thinking of something like an in-memory registry of scalar names to encoder/decoders would and that would be initialized from user code. But, there really isn't an object to hook into without introducing a new runtime dependency.

For my specific case, I would be able to get by by indicating that "uuid" == "ID" or "uuid" == "string", and not really require custom serializers. For a more general approach, `bsDecoder` already gives some of this functionality on a local basis. Would it make sense to model the global converters on that?

**Comment by jfrolich** [comment]
This is implemented now #40
