### ISSUE TITLE
Unused variables warnings

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql_ppx#64]
```
  Warning number 32
  (No file name)

  unused value query.

  Warning number 32
  (No file name)

  unused value make.

  Warning number 32
  (No file name)

  unused value makeWithVariables.

  Warning number 32
  (No file name)

  unused value query.

  Warning number 32
  (No file name)

  unused value make.

  Warning number 32
  (No file name)

  unused value makeWithVariables.

  Warning number 32
  (No file name)

  unused value query.

  Warning number 32
  (No file name)

  unused value make.

  Warning number 32
  (No file name)

  unused value makeWithVariables.
```

When I only expose what I need using an interface file, I get a lot of warnings of unused variables. Perhaps this can be solved by not declaring variables on the root, but only within the module.

**Comment by jfrolich** [comment]
Closing this, AFAK this has been fixed in 1.0.

**Comment by joprice** [comment]
I'm interested in this fix. How do you install the 1.0 beta releases? They don't seem to appear on npm.

**Comment by jfrolich** [comment]
They are published on the `@next` tag (https://www.npmjs.com/package/@baransu/graphql_ppx_re).

**Comment by jsiebern** [comment]
Regarding these errors: Keep in mind that the hover values for rendered gql (like on fragments) also need to be exposed for RLS to be able to read them. I've been thinking about pushing all of them inside some `HELPERS_DO_NOT_TOUCH` module (bad name, but you get the gist).
