### ISSUE TITLE
Using @bsRecord when certain fields are optional

### ISSUE THREAD

**Issue by dylanirlbeck** [reasonml-community/graphql_ppx#78]
So I'm getting a weird error from the following code snippet:

```reason
type stuff = {
  id: string,
  name: option(string),
  fileName: string,
};

module GetStuff = [%graphql
  {|
    query Stuffs {
      stuffs @bsRecord {
        id
        name
        fileName
      }
    }
  |}
];
```

The error I get is this:

```
  We've found a bug for you!

    id
    **name**
    fileName

  This has type:
    string
  But somewhere wanted:
    option(string)
```

Does anyone know why this might be happening? Thanks in advance!

**Comment by baransu** [comment]
Is the type of the name `String` or `String!`? To use `@bsRecord` you have to provide all fields and they have to have the same Reason and GraphQL type signatures like `String` is `option(string)` and `String!` is `string`.

**Comment by dylanirlbeck** [comment]
What's odd is that the type of `name` was `String` in GraphQL. This issue is now solved though --- `name` was removed from the schema and as such I no longer get the error. I'm thinking I had typed some stuff wrong on the GraphQL side and/or I didn't regenerate my schema (I'm working with TypeORM).

In any event, thanks for the prompt response!

**Comment by dylanirlbeck** [comment]
@baransu On a side note, could you consider putting this exact sentence into the `README`?

> To use @bsRecord you have to provide all fields and they have to have the same Reason and GraphQL type signatures like String is option(string) and String! is string.

It may feel obvious, but for beginners like myself that's just one less point of confusion. I'd be happy to open a PR for this small change, depending on how you feel.

**Comment by baransu** [comment]
Would be great to have that! Reopening until this addition lands in README 😉

**Comment by jfrolich** [comment]
We are revamping the documentation for 1.0, closing for now.
