### ISSUE TITLE
@bsRecord with two different types of the same structure

### ISSUE THREAD

**Issue by andrewlinfoot** [reasonml-community/graphql_ppx#82]
Hey all, I'm working on converting some of our app queries from Js.t to @bsRecord syntax. I'm running into and issue where @bsRecord doesn't see to be mapping to the right record type when I have two fields of the same name/structure. 

Here is the code:
```
type user = {
  id: string,
  firstName: option(string),
  lastName: option(string),
};

type actor = {user: option(user)};

type target = {user};

type activity = {
  id: string,
  createdAt: Js.Date.t,
  type_: [ | `USER_POST | `CALENDLY | `APPLICATION],
  body: option(string),
  actor: option(actor),
  target,
};

module Fragment = [%graphql
  {|
  fragment Activity on Activity @bsRecord {
    id
        createdAt  @bsDecoder(fn: "Decoders.dateDecoder")
        type_: type
        body
        actor @bsRecord {
          user @bsRecord {
            id
            firstName
            lastName
          }
        }

        target @bsRecord {
          user @bsRecord  {
            id
            firstName
            lastName
          }
        }
  }
  |}
];
```

The code compiles fine if I only want the actor or target fields individually but if I try to have both, I get the following error:
```
  26 ┆ body
  27 ┆ actor @bsRecord {
  28 ┆   user @bsRecord {
  29 ┆     id
  30 ┆     firstName
  31 ┆     lastName
  32 ┆   }
  33 ┆ }
  34 ┆

  This has type:
    option(user)
  But somewhere wanted:
    user
```
It doesn't seem to pick up the actor should have an optional user and target should have a non-optional user.

Here are the graphql type defs:

```
  type ActivityActor {
    user: User
  }

  type ActivityTarget {
    user: User!
  }

  type Activity {
    id: ID!
    createdAt: Date!
    type: ActivityType!
    body: String
    actor: ActivityActor
    target: ActivityTarget!
  }
```

Would love any help on this one. Once again, not sure if this an issue with my syntax or an actual bug? 😅

Thanks a ton!

**Comment by jfrolich** [comment]
You can try the records PR branch (npm package `@jfrolich/graphql_ppx_re`). This will automatically create the record types for you. Documentation here: https://github.com/jfrolich/graphql_ppx_re/tree/records.

**Comment by andrewlinfoot** [comment]
Woah, that looks awesome! Thanks @jfrolich!!

Is that fork more actively maintained than this one? Is it on the roadmap to merge the two?

**Comment by jfrolich** [comment]
Yes. It is a bit early because it's a big change. There will probably an official beta soon. The fork is just under my namespace to have a working NPM package that my startup uses in production.

**Comment by andrewlinfoot** [comment]
@jfrolich so awesome! I'll probably wait until the official beta to switch and leave that one type in Js.t for now since I was able to convert the rest over. Excited to check it out when live! :)

**Comment by MargaretKrutikova** [comment]
I just tested your fork, @jfrolich, and it is just beyond comprehension, so cool with `@argumentDefinitions` and the record support! Thanks for all the work, can't imagine the amount of effort you put into it... Is there any estimate on when it is going to be merged into the main repo?

And can people give feedback/create issues for your fork in this repo or is there a better way?

**Comment by jfrolich** [comment]
@MargaretKrutikova: Great you are trying it out! My company is using it in production already. Record support was quite an architecture change so there are a few more breaking changes coming up before it's "stable", so want to keep it in beta until then, and also do a bit more polish like documentation etc. and release that as 1.0. No real timeline, but hopefully soon!

You can just open issues here. Features will be mostly added to the 1.0 branch anyway. I will try to keep some of the larger changes to 1.0 in separate pull-request as well (like #98).

**Comment by jfrolich** [comment]
@MargaretKrutikova: Btw try out the official 1.0 beta and not my "@jfrolich" fork. That one is not used anymore as we are now having the official beta release.

**Comment by jfrolich** [comment]
`@ppxAs` in 1.0 is addressing this. (And of course also the option to compile everything to records).
