### ISSUE TITLE
Possible change for required named args with default values

### ISSUE THREAD

**Issue by studious** [reasonml-community/graphql_ppx#90]
Would you consider required args that also have default values as passing or failing validation?

After migrating to graphql_ppx_re from graphql_ppx I have been getting errors for this redundant but allowable case.

I know default values are supposed to be for optional arguments but there is nothing stopping the schema author from making something required and also providing a default value and the spec below says...

> Arguments can be required. An argument is required if the argument type is non‐null and does not have a default value. Otherwise, the argument is optional.
> https://spec.graphql.org/June2018/#sec-Required-Arguments

The graphql playground will not complain about missing args if a default is present.

For now I will wander around my code and add the default value from the schema to the arg params. But it might be nice to let these pass.

**Comment by jfrolich** [comment]
Yes I think we should not require the argument when a default is present.

**Comment by baransu** [comment]
It should be a simple change here:
 https://github.com/reasonml-community/graphql_ppx/blob/fa8f5a09210d0c4f8cf208f0a750dc40e01f8426/src/base/rule_all_required_arguments.re#L25

We have to check also if `am_default_value` is `Some` or `None`.

**Comment by jfrolich** [comment]
Let put this on the list for 1.0

**Comment by jsiebern** [comment]
Fixed in #122
