### ISSUE TITLE
`definition` "broken" in 1.0

### ISSUE THREAD

**Issue by gaku-sei** [reasonml-community/graphql_ppx#95]
I just tried updating to graphql_ppx 1.0, but this, previously working, code:

```reason
module UpdateAvatar = [%graphql
  {|
    mutation UpdateAvatar($id: ID!, $base64: String!) {
      updateIdentityPicture(encodedImage: $base64, id: $id) {
        id
      }
    }
  |}
];
```

Now raises this error when used with ReasonUrql:

<img width="648" alt="Capture d’écran 2020-03-16 à 18 22 20" src="https://user-images.githubusercontent.com/3982371/76741777-76504380-67b3-11ea-91ba-3c2eb85bf3a5.png">

the previous type of `definition` for the above module was:

```reason
(Js.Json.t => UpdateAvatar.t, string,
    (Js.Json.t => 'a, ~id: string, ~base64: string, unit) => 'a)
```

But it's now (notice the `~f` labelled parameter:

```reason
(Js.Json.t => UpdateAvatar.t, string,
    (~f: Js.Json.t => 'a, ~id: string, ~base64: string, unit) => 'a)
```

This seems to be a major breaking change (?)

**Comment by jfrolich** [comment]
Yes. This is a breaking change and `reason-urql` has not been updated yet. The 1.0 beta will be unstable for a while as we iterate on it.

**Comment by gaku-sei** [comment]
Thank you for your reply @jfrolich 😃
