### ISSUE TITLE
Fix location of types for better editor support

### ISSUE THREAD

**Issue by jfrolich** [reasonml-community/graphql_ppx#96]
I tried to pass locs as good as possible, but maybe I do something wrong or maybe the locs are derived incorrectly further in the internals.

Any thoughts?

![2020-03-19 10 05 17](https://user-images.githubusercontent.com/579279/77024437-7b86db80-69c9-11ea-86e5-105d08962c34.gif)

**Comment by jsiebern** [comment]
Added in #118
